### ISSUE TITLE
Trying to use embedded BoltBrowser in Docker Image but claims no cmd

### ISSUE THREAD

**Issue by taw123** [raesene/alpine-containertools#3]
Per doc, mounted the vol via interactive shell, but can't seem to access BoltBrowser

```
docker run -it raesene/alpine-containertools /bin/bash

bash-5.1# boltbrowser --help
bash: boltbrowser: command not found

bash-5.1# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Tried another tool from container (helm) which does work so obviously the container is started and no issues with it.
```
bash-5.1# helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

```

Also given how you created this and for YOUR security purposes it APPEARS(?) you didn't construct the container with any provision for volume mounting. Is this true or is it just not documented (feel free to fault me for not looking into the dockerfile config since I THINK that would allow me to see if you do have a provision to pass a mount to the container)...  Long story short just looking for a quick and dirty way to use BoltBrowser to examine and my Portainer.db backup and extract all the yaml files so I can backup my endpoint and restore it to a new host as part of my server/data migration.

Thanks for any help you can point me at!
--T

**Comment by raesene** [comment]
Ah sorry, this is the README not being up to date. I had to remove boltbrowser as the source I was getting it from (` https://bullercodeworks.com/downloads/boltbrowser/boltbrowser.linux64`) vanished. I'll update the README to reflect it not being there any more.

As to mounts, I generally just add those when I run the container (either via the `-v` switch in Docker or included in a Kubernetes manifest.

**Comment by raesene** [comment]
Removed reference to boltbrowser from README https://github.com/raesene/alpine-containertools/commit/5600c7dd0558c1a0db890596bcd1852c62c8598f
